substitutions:
  device_name: closet_motion
  upper_device_name: Closet Motion

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini

wifi: !include include/wifi.yaml

captive_portal:

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
# api:

ota:

mqtt: !include include/mqtt.yaml

binary_sensor:
  - platform: gpio
    pin: D6
    name: $upper_device_name
    device_class: motion
    filters:
      - delayed_on: 20ms
    state_topic: $device_name/state
    
sensor:
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s
    expire_after: 60min
    icon: mdi:wifi
  
button:
  - platform: restart
    name: $upper_device_name Restart