substitutions:
  device_name: esp32cam
  upper_device_name: ESP32 Cam

esphome:
  name: $device_name
  platform: ESP32
  board: esp32cam

wifi: !include include/wifi.yaml

captive_portal:

# web_server:
#   port: 80

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:

ota:
      
switch:
  - platform: restart
    name: $upper_device_name Restart
    
sensor:
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s
    
esp32_camera:
  name: $upper_device_name
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  resolution: 320x240
  jpeg_quality: 20
  max_framerate: 10 fps




