substitutions:
  device_name: esp32_test
  upper_device_name: ESP32 Test

esphome:
  name: $device_name
  platform: ESP32
  # board: esp32doit-devkit-v1
  # board: wemos_d1_mini32
  board: esp32dev

wifi: !include include/wifi.yaml

captive_portal:

web_server:
  port: 80

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
# api:

ota:

mqtt: !include include/mqtt.yaml
      
switch:
  - platform: restart
    name: $upper_device_name Restart

esp32_ble_tracker:

ble_client:
  - mac_address: ed:c1:c6:bb:2c:74
    id: soma_shade
    
sensor:
  - platform: ble_client
    ble_client_id: soma_shade
    name: "Soma battery level"
    service_uuid: '180f'
    characteristic_uuid: '2a19'
    icon: 'mdi:battery'
    unit_of_measurement: '%'
    filters:
      - filter_out: nan
      
  - platform: ble_client
    ble_client_id: soma_shade
    name: "Soma 1800-2A00"
    service_uuid: '1800'
    characteristic_uuid: '2A00'
    filters:
      - filter_out: nan
      
  - platform: ble_client
    ble_client_id: soma_shade
    name: "Soma 1800-2A01"
    service_uuid: '1800'
    characteristic_uuid: '2A01'
    filters:
      - filter_out: nan
      
  - platform: ble_client
    ble_client_id: soma_shade
    name: "Soma 1800-2A04"
    service_uuid: '1800'
    characteristic_uuid: '2A04'
    filters:
      - filter_out: nan
      
  - platform: ble_client
    ble_client_id: soma_shade
    name: "Soma 1801-2A05"
    service_uuid: '1801'
    characteristic_uuid: '2A05'
    filters:
      - filter_out: nan
      
  - platform: ble_client
    ble_client_id: soma_shade
    name: "Soma 180A-2A29"
    service_uuid: '180A'
    characteristic_uuid: '2A29'
    filters:
      - filter_out: nan
      
  - platform: ble_client
    ble_client_id: soma_shade
    name: "Soma 180A-2A25"
    service_uuid: '180A'
    characteristic_uuid: '2A25'
    filters:
      - filter_out: nan
      
  - platform: ble_client
    ble_client_id: soma_shade
    name: "Soma 180A-2A27"
    service_uuid: '180A'
    characteristic_uuid: '2A27'
    filters:
      - filter_out: nan
      
  - platform: ble_client
    ble_client_id: soma_shade
    name: "Soma 180A-2A26"
    service_uuid: '180A'
    characteristic_uuid: '2A26'
    filters:
      - filter_out: nan
      
  - platform: ble_client
    ble_client_id: soma_shade
    name: "Soma 180A-2A28"
    service_uuid: '180A'
    characteristic_uuid: '2A28'
    filters:
      - filter_out: nan
    
  
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s
    
binary_sensor:
  # Presence based on MAC address
  - platform: ble_presence
    mac_address: ed:c1:c6:bb:2c:74
    name: "ESP32 BLE Tracker Soma Shade"
