substitutions:
  device_name: esp32_test
  upper_device_name: ESP32 Test

esphome:
  name: $device_name
  platform: ESP32
  # board: esp32doit-devkit-v1
  board: wemos_d1_mini32

wifi: !include include/wifi.yaml

captive_portal:

web_server:
  port: 80

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
# api:

ota:

mqtt: 
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  # Needed when using deep sleep mode
  birth_message:
    topic: $device_name/birthdisable
    payload: disable
  will_message:
    topic: $device_name/willdisable
    payload: disable
      
switch:
  - platform: restart
    name: $upper_device_name Restart

esp32_ble_tracker:

i2c:
    
sensor:

  - !include include/sht3xd-45.yaml
  
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s
    
  - platform: ruuvitag
    mac_address: !secret trailer_fridge_ruuvi_mac
    temperature:
      name: $upper_device_name Fridge Temperature
      expire_after: 60min
      # on_value:  # Device will stay awake until Ruuvi values are published (or deep sleep timer is reached)
      #   then:
      #     - logger.log: "  Fridge Temp Published!!"
      #     - deep_sleep.enter: deep_sleep_1
    measurement_sequence_number:
      name: $upper_device_name Fridge Measurement Sequence Number
      expire_after: 60min
      
deep_sleep: 
  run_duration: 60s  ## this is a long duration, trying to pickup the Ruuvi BLE beacon
  sleep_duration: 15min
  id: deep_sleep_1