substitutions:
  device_name: esp32_test
  upper_device_name: ESP32 Test

esphome:
  name: $device_name
  platform: ESP32
  # board: esp32doit-devkit-v1
  board: esp32dev

wifi: !include include/wifi.yaml

## Note: I had to enable "multicast routing" on my router for mDNS to work for the ESP32S Devkit-v1

captive_portal:

web_server:
  port: 80

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
# api:

ota:

mqtt: !include include/mqtt.yaml
      
switch:
  - platform: restart
    name: $upper_device_name Restart
    
sensor:
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s

output:
  platform: gpio
  pin: 2
  id: onboard_led
  # inverted: True
  
light:
  - platform: binary
    name: $upper_device_name Onboard LED
    output: onboard_led


  # - platform: fastled_clockless
  #   chipset: WS2811
  #   pin: GPIO15
  #   num_leds: 10
  #   rgb_order: GRB
  #   name: $upper_device_name LED one strip
  #   id: $device_name
  #   state_topic: $device_name/light/$device_name/state
  #   command_topic: $device_name/light/$device_name/command
  #   effects: !include include/led_effects.yaml

  - platform: fastled_clockless
    chipset: WS2811
    pin: GPIO02
    num_leds: 37
    rgb_order: GRB
    name: $upper_device_name LED seg 0
    id: led_seqment_0
    state_topic: $device_name/light/led_seqment_0/state
    command_topic: $device_name/light/led_seqment_0/command
    effects: !include include/led_effects.yaml

  - platform: fastled_clockless
    chipset: WS2811
    pin: GPIO15
    num_leds: 37
    rgb_order: GRB
    name: $upper_device_name LED seg 1
    id: led_seqment_1
    state_topic: $device_name/light/led_seqment_1/state
    command_topic: $device_name/light/led_seqment_1/command
    effects: !include include/led_effects.yaml

  - platform: fastled_clockless
    chipset: WS2811
    pin: GPIO12
    num_leds: 37
    rgb_order: GRB
    name: $upper_device_name LED seg 2
    id: led_seqment_2
    state_topic: $device_name/light/led_seqment_2/state
    command_topic: $device_name/light/led_seqment_2/command
    effects: !include include/led_effects.yaml

  - platform: fastled_clockless
    chipset: WS2811
    pin: GPIO13
    num_leds: 37
    rgb_order: GRB
    name: $upper_device_name LED seg 3
    id: led_seqment_3
    state_topic: $device_name/light/led_seqment_3/state
    command_topic: $device_name/light/led_seqment_3/command
    effects: !include include/led_effects.yaml
    
  - platform: partition
    name: $upper_device_name LED Partition Light
    segments:
      - id: led_seqment_0
        from: 0
        to: 36
      - id: led_seqment_1
        from: 0
        to: 36
      - id: led_seqment_2
        from: 0
        to: 36
      - id: led_seqment_3
        from: 0
        to: 36
    state_topic: $device_name/light/partition/state
    command_topic: $device_name/light/partition/command
    effects: !include include/led_effects.yaml
    