substitutions:
  device_name: ir_receiver
  upper_device_name: IR Receiver

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini

wifi: !include include/wifi.yaml

captive_portal:

web_server:
  port: 80

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
# api:

ota:

mqtt: !include include/mqtt.yaml
    
output: !include include/onboard_led.yaml
    
sensor:
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s
    icon: mdi:wifi
      
remote_receiver:
  pin: 
    number: GPIO2
    inverted: True
  dump: all
  id: recvr1
  
# binary_sensor:
  # - platform: remote_receiver
  #   receiver_id: recvr1
  #   name: "Office AC Power Button"
  #   nec:
  #     address: 0x80FF
  #     command: 0x48B7
     
  
button:
  - platform: restart
    name: $upper_device_name Restart 
