substitutions:
  device_name: lr_ac
  upper_device_name: Living Room AC
  climate_id: lrac
  switch_prefix: LR

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini

wifi: !include include/wifi.yaml

captive_portal:

web_server:
  port: 80

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
# api:

ota:

mqtt: !include include/mqtt.yaml
    
output: !include include/onboard_led.yaml
    
<<: !include include/fujitsu_climate.yaml
    
sensor:
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 30min
    icon: mdi:wifi
      
switch: !include include/fujitsu_switches.yaml

button:
  - platform: restart
    name: $upper_device_name Restart