substitutions:
  device_name: lr_ir
  upper_device_name: Living Room IR
  switch_prefix: IR
  tv_state_topic: $device_name/living_room_tv/state

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini

wifi: !include include/wifi_iot.yaml

captive_portal:

web_server:
  port: 80

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
# api:

ota:

mqtt: !include include/mqtt.yaml
    
output: !include include/onboard_led.yaml
    
sensor:
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s
    icon: mdi:wifi
    
text_sensor:
  - platform: mqtt_subscribe
    id: lr_tv_state
    topic: $tv_state_topic
    icon: mdi:television
    
# binary_sensor:
#   - platform: template
#     name: $upper_device_name TV State
#     icon: mdi:television
#     lambda: |-
#       if (id(lr_tv_state).state == "on") {
#         return true;
#       } else {
#         return false;
#       }
      
script: 
  # While this script is running the receiver will ignore any power codes
  - id: code_repeat_block
    then:
      - delay: 1.5s
      
remote_receiver:
  pin:
    number: GPIO2 # D4
    inverted: true
    mode:
      input: true
      pullup: true
  # dump: all
  on_sony:
    lambda: |-
      if (x.data == 0xA90){
        if ( id(code_repeat_block).is_running() == false){
          id(code_repeat_block).execute();
          if (id(lr_tv_state).state == "on") {
            id(mqtt_client).publish("lr_ir/living_room_tv/state", "off");
          } else {
            id(mqtt_client).publish("lr_ir/living_room_tv/state", "on");
          }
        }
      }
    
remote_transmitter:
  pin: GPIO0  # D3
  carrier_duty_percent: 50%
  id: trans
      
button:
  - platform: restart
    name: $upper_device_name Restart
    
  - platform: template
    name: $upper_device_name Sony TV Power
    on_press:
      remote_transmitter.transmit_sony:
        data: 0xA90
        nbits: 12
        repeat:
          times: 2
    
  - platform: template
    name: $upper_device_name Sony TV Mute
    on_press:
      remote_transmitter.transmit_sony:
        data: 0x290
        nbits: 12
        repeat:
          times: 2
    
  - platform: template
    name: $upper_device_name TV-Cable On
    on_press:
        #. TV power on, Cable Menu, Cable power twice
      - if:
          condition:
            # Checks if tv is already on
            text_sensor.state:
              id: lr_tv_state
              state: 'off'
          then:
            - remote_transmitter.transmit_sony:
                data: 0xA90
                nbits: 12
                repeat:
                  times: 2
            - delay: 300ms
      - remote_transmitter.transmit_raw:
          code: [ 8989, -4488, 502, -4489, 505, -2225, 505, -2232, 475, -4515, 
                  476, -4518, 500, -2236, 496, -2227, 506, -2228, 505, -2228, 
                  505, -2229, 503, -2229, 502, -2231, 502, -2231, 501, -4491, 
                  500, -4490, 502, -2228, 505]
          carrier_frequency: 38kHz
      - delay: 300ms
      - remote_transmitter.transmit_raw:
          code: [ 8900,-4300, 600,-2150, 600,-4300, 600,-2100, 600,-4350, 600,-2150, 
                 600,-2150, 600,-2150, 600,-2100, 600,-2150, 600,-2150, 600,-2150,
                 600,-2150, 600,-2150, 600,-4300, 600,-4300, 600,-2150, 600]
          carrier_frequency: 38kHz
      - delay: 300ms
      - remote_transmitter.transmit_raw:
          code: [ 8900,-4300, 600,-2150, 600,-4300, 600,-2100, 600,-4350, 600,-2150, 
                 600,-2150, 600,-2150, 600,-2100, 600,-2150, 600,-2150, 600,-2150,
                 600,-2150, 600,-2150, 600,-4300, 600,-4300, 600,-2150, 600]
          carrier_frequency: 38kHz
    
  - platform: template
    name: $upper_device_name TV-Cable Off
    on_press:
        #. TV power on, Cable Menu, Cable power one
      - if:
          condition:
            # Only turn off the TV if it is actually on
            text_sensor.state:
              id: lr_tv_state
              state: 'on'
          then:
            - remote_transmitter.transmit_sony:
                data: 0xA90
                nbits: 12
                repeat:
                  times: 2
            - delay: 300ms
      - remote_transmitter.transmit_raw:
          code: [ 8989, -4488, 502, -4489, 505, -2225, 505, -2232, 475, -4515, 
                  476, -4518, 500, -2236, 496, -2227, 506, -2228, 505, -2228, 
                  505, -2229, 503, -2229, 502, -2231, 502, -2231, 501, -4491, 
                  500, -4490, 502, -2228, 505]
          carrier_frequency: 38kHz
      - delay: 300ms
      - remote_transmitter.transmit_raw:
          code: [ 8900,-4300, 600,-2150, 600,-4300, 600,-2100, 600,-4350, 600,-2150, 
                 600,-2150, 600,-2150, 600,-2100, 600,-2150, 600,-2150, 600,-2150,
                 600,-2150, 600,-2150, 600,-4300, 600,-4300, 600,-2150, 600]
          carrier_frequency: 38kHz
      
  
  
  
  
  
  
  
  