substitutions:
  device_name: lr_ir
  upper_device_name: Living Room IR
  switch_prefix: IR

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini

wifi: !include include/wifi.yaml

captive_portal:

web_server:
  port: 80

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
# api:

ota:

mqtt: !include include/mqtt.yaml
    
output: !include include/onboard_led.yaml
    
sensor:
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s
    icon: mdi:wifi
    
remote_transmitter:
  pin: GPIO12  # D6
  carrier_duty_percent: 50%
  id: $device_name
      
switch:
- platform: restart
  name: $upper_device_name Restart