substitutions:
  device_name: outdoor
  upper_device_name: Outdoor

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini_pro
  on_boot:
    priority: 500.00
    then:
      - delay: 500ms

wifi: !include include/wifi.yaml

captive_portal:

# Enable logging
logger:
  level: WARN

# Enable Home Assistant API
# api:

ota:

web_server:
  port: 80

mqtt: !include include/mqtt_deep_sleep_device_name.yaml

i2c:

sensor:
  - !include include/bme280.yaml
  - !include include/bme280_sea_level_pressure.yaml
  - !include include/bme280_dew_point.yaml

  - platform: adc
    pin: A0
    filters:
      - multiply: 100
    unit_of_measurement: "%"
    icon: mdi:battery
    name: $upper_device_name Battery
    update_interval: 60s
    expire_after: 30min
    state_topic: $device_name/battery/state
    
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s
  
switch:
  - platform: restart
    name: $upper_device_name Restart
    
deep_sleep: !include include/deep_sleep_15.yaml
