substitutions:
  device_name: rf-receive
  upper_device_name: RF Receiver

esphome:
  name: $device_name
  platform: ESP32
  board: esp32doit-devkit-v1

wifi: !include include/wifi.yaml

captive_portal:

web_server:
  port: 80

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
# api:

ota:

mqtt: 
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  # Needed when using deep sleep mode
  birth_message:
    topic: $device_name/birthdisable
    payload: disable
  will_message:
    topic: $device_name/willdisable
    payload: disable
      
button:
  - platform: restart
    name: $upper_device_name Restart
      
switch:
  - platform: template
    name: RV Light
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
          transmitter_id: transmitter
          code: '1100011000100101011001000'
          protocol: 1  
          # repeat: 3

remote_receiver:
  id: receiver
  pin: 
    number: GPIO12
    # inverted: true
  dump: rc_switch
  # Settings to optimize recognition of RF devices
  tolerance: 50%
  filter: 250us
  idle: 4ms
  buffer_size: 4kb
  
  #Received RCSwitch Raw: protocol=1 data='110001100010010101100100'
  
remote_transmitter:
  id: transmitter
  pin: GPIO13
  # RF uses a 100% carrier signal
  carrier_duty_percent: 100%
  
 
  