substitutions:
  device_name: table_display
  upper_device_name: Table Display

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini

wifi: !include include/wifi.yaml

captive_portal:

web_server:
  port: 80

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
# api:

ota:

mqtt: !include include/mqtt.yaml

time:
  - platform: sntp
    id: esptime
    timezone: America/Detroit
      
switch:
  - platform: restart
    name: $upper_device_name Restart
    
sensor:
  # - platform: homeassistant
  #   id: inside_temperature
  #   entity_id: sensor.living_room_temperature
  #   internal: true

  # - platform: homeassistant
  #   id: outside_temperature
  #   entity_id: sensor.dark_sky_temperature
  #   internal: true

  - platform: mqtt_subscribe
    id: inside_temperature_2
    topic: lr/sht3xd/temperature/state
    filters:
      - lambda: return x * (9.0/5.0) + 32.0;

  - platform: mqtt_subscribe
    id: outside_temperature_2
    topic: outdoor/temperature/state
    filters:
      - lambda: return x * (9.0/5.0) + 32.0;
  
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s
    
font:
  - file: 'fonts/arial.ttf'
    id: font1
    size: 10

  - file: 'fonts/arial.ttf'
    id: font2
    size: 36

  - file: 'fonts/arial.ttf'
    id: font3
    size: 14
    
i2c:

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    reset_pin: D0
    address: 0x3C
    lambda: |-
      // Print "Living Room" in top center.
      it.printf(64, 0, id(font1), TextAlign::TOP_CENTER, "Living Room");

      // Print time in HH:MM format
      it.strftime(0, 55, id(font2), TextAlign::BASELINE_LEFT, "%I:%M", id(esptime).now());

      // Print inside temperature (from homeassistant sensor)
      if (id(inside_temperature_2).has_state()) {
        it.printf(127, 23, id(font3), TextAlign::TOP_RIGHT , "%.1f°", id(inside_temperature_2).state);
      }

      // Print outside temperature (from homeassistant sensor)
      if (id(outside_temperature_2).has_state()) {
        it.printf(127, 60, id(font3), TextAlign::BASELINE_RIGHT , "%.1f°", id(outside_temperature_2).state);
      }