substitutions:
  device_name: temp_compare
  upper_device_name: Temp Compare

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini

wifi: !include include/wifi.yaml

captive_portal:

web_server:
  port: 80

logger:
  level: WARN

ota:

# web_server:
#   port: 80

mqtt: !include include/mqtt_deep_sleep.yaml

# Enable Home Assistant API
# api:

i2c:

sensor:
  - platform: sht3xd
    temperature:
      name: "Temp Compare SHT30D Temperature"
      expire_after: 60min
      accuracy_decimals: 2
      state_topic: $device_name/sht3xd/temperature/state
    humidity:
      name: "Temp Compare SHT30D Humidity"
      expire_after: 60min
      accuracy_decimals: 2
      icon: mdi:water-percent
      state_topic: $device_name/sht3xd/humidity/state
    update_interval: 15min
    
  - platform: bme280
    temperature:
      name: "Temp Compare BME280 Temperature"
      id: bme280_temperature
      oversampling: 16x
      expire_after: 60min
      accuracy_decimals: 2
      state_topic: $device_name/bme280/temperature/state
    pressure:
      name: "Temp Compare BME280 Pressure"
      id: bme280_pressure
      expire_after: 60min
      unit_of_measurement: "mbar"
      accuracy_decimals: 2
      icon: mdi:gauge
      state_topic: $device_name/bme280/pressure/state
    humidity:
      name: "Temp Compare BME280 Humidity"
      expire_after: 60min
      accuracy_decimals: 2
      icon: mdi:water-percent
      state_topic: $device_name/bme280/humidity/state
    address: 0x76
    update_interval: 10min
  - platform: template
    name: "Temp Compare BME280 Equiv Sea Level Pressure"
    lambda: |-
      const float STANDARD_ALTITUDE = 204; // in meters, see note
      return id(bme280_pressure).state / powf(1 - ((0.0065 * STANDARD_ALTITUDE) /
        (id(bme280_temperature).state + (0.0065 * STANDARD_ALTITUDE) + 273.15)), 5.257); // in hPa
    update_interval: 10min
    unit_of_measurement: 'mBar'
    expire_after: 60min
    accuracy_decimals: 2
    icon: mdi:gauge
    state_topic: $device_name/bme280/equiv_sea_level_pressure/state
    
  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s
    expire_after: 60min
    icon: mdi:wifi
  
switch:
  - platform: restart
    name: $upper_device_name Restart
    
deep_sleep: !include include/deep_sleep_15.yaml

