substitutions:
  device_name: trailer
  upper_device_name: Trailer
  ip_address: 192.168.37.208

esphome:
  name: $device_name
  platform: ESP32
  board: wemos_d1_mini32

wifi: 
  networks:
  - ssid: $gentryrv_ssid
    password: $gentryrv_password
  - ssid:  !secret wifi_iot_ssid
    password: !secret wifi_iot_password
    manual_ip:
      static_ip: $ip_address
      gateway: 192.168.37.1
      subnet: 255.255.255.0
      
# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $upper_device_name
    password: !secret hotspot_password

captive_portal:

# Enable logging
logger:
  level: ERROR

# Enable Home Assistant API
# api:

# ota: ## No OTA - memory is tight

mqtt: !include include/mqtt_deep_sleep.yaml

globals:
  - id: ruuvi_count
    type: int
    restore_value: no
    initial_value: '0'

i2c:
    
esp32_ble_tracker:

sensor:

  # - !include include/sht3xd-45.yaml

  - platform: adc
    pin: A0
    filters:
      - lambda: return 100;    ## Connected to 5v external power supply - always reports 100%
    unit_of_measurement: "%"
    name: $upper_device_name Battery
    device_class: battery
    update_interval: 60s
    expire_after: 60min
    state_topic: $device_name/battery/state

  - platform: wifi_signal
    name: $upper_device_name WiFi Signal
    update_interval: 60s
    expire_after: 60min
    state_topic: $device_name/sensor/wifi_signal/state
    
  - platform: ruuvitag
    mac_address: !secret trailer_fridge_ruuvi_mac
    temperature:
      name: $upper_device_name Fridge Temperature
      expire_after: 60min
      device_class: "temperature"
      # Device will stay awake until Ruuvi values are received the 2nd time (or deep sleep timer is reached)
      # Used 2nd time as the deep sleep happens before the values are published in MQTT
      on_value:  
        then:
          - lambda: |-
              ESP_LOGD("sleepy", "  Fridge Temp Published!:");
              id(ruuvi_count) += 1;
              if(id(ruuvi_count) > 1 ){
                id(deep_sleep_1).begin_sleep();
              }
    # I certainly don't need all of these other attributes, but they're fun!!
    humidity:
      name: $upper_device_name Fridge Humidity
      expire_after: 60min
    # pressure:
    #   name: $upper_device_name Fridge Pressure
    #   expire_after: 60min
    # acceleration:
    #   name: $upper_device_name Fridge Acceleration
    #   expire_after: 60min
    # acceleration_x:
    #   name: $upper_device_name Fridge Acceleration X
    #   expire_after: 60min
    # acceleration_y:
    #   name: $upper_device_name Fridge Acceleration Y
    #   expire_after: 60min
    # acceleration_z:
    #   name: $upper_device_name Fridge Acceleration Z
    #   expire_after: 60min
    battery_voltage:
      name: $upper_device_name Fridge Battery Voltage
      expire_after: 60min
    # tx_power:
    #   name: $upper_device_name Fridge TX Power
    #   expire_after: 60min
    # movement_counter:
    #   name: $upper_device_name Fridge Movement Counter
    #   expire_after: 60min
    # measurement_sequence_number:
    #   name: $upper_device_name Fridge Measurement Sequence Number
    #   expire_after: 60min
    
deep_sleep: 
  run_duration: 180s  ## this is a long duration, trying to pickup the Ruuvi BLE beacon
  sleep_duration: 15min
  id: deep_sleep_1
      
button:
  - platform: restart
    name: $upper_device_name Restart
